orient/cup/urls.py
from django.conf.urls import url, patterns

from .views import IndexView, OrganizerView, OrganizerUpdateView, OrganizerCreateView,\
    MarathonDetailView, RunnerDetailView, latest_m

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^or/(?P<pk>\d+)$', OrganizerView.as_view(), name='organizer'),
    url(r'^or-u/(?P<pk>\d+)$', OrganizerUpdateView.as_view(), name='organizer_update'),
    url(r'^or-c', OrganizerCreateView.as_view(), name='organizer_create'),
    url(r'^marathon/(?P<pk>\d+)$', MarathonDetailView.as_view(), name='marathon_runners'),
    url(r'^runner/(?P<pk>\d+)$', RunnerDetailView.as_view(), name='runner'),
    url(r'^latestm$', latest_m, name='latest_m'),
)

orient/orient/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'', include('cadmin.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
    url(r'^cup/', include('cup.urls', namespace='cup')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

orient/orient/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
<!doctype html>
<html>
    <head>
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        {% addtoblock "css" %}
            <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css" type="text/css" media="all">
        {% endaddtoblock %}
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        <div class="container">
            <div id="header">
                <div id="mainmenu">
                    <ul class="nav">
                        {% show_menu 0 100 100 100 %}
                    </ul>
                </div>
            </div>
            {% block content %}{% endblock content %}
        </div>
        {% addtoblock "js" %}
            <script src="{{ STATIC_URL }}djangocms_cup/js/jquery-2.1.4.min.js" type="text/javascript"></script>
            <script src="{{ STATIC_URL }}djangocms_cup/jquery-validation-1.14.0/dist/jquery.validate.min.js" type="text/javascript"></script>
            <script src="{{ STATIC_URL }}djangocms_cup/jquery-validation-1.14.0/dist/localization/messages_pl.min.js" type="text/javascript"></script>
        {% endaddtoblock %}
        {% addtoblock "js" %}
            <script type="text/javascript">
                var url_cup_organizer = "{% url 'cup:organizer' 1 %}";
                var url_cup_organizer_update = "{% url 'cup:organizer_update' 1 %}";
                var url_cup_organizer_create = "{% url 'cup:organizer_create' %}";
            </script>
            <script src="{{ STATIC_URL }}djangocms_cup/js/custom.js" type="text/javascript"></script>
        {% endaddtoblock %}
        {% render_block "js" %}
    </body>
</html>

orient/orient/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

orient/orient/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
    <div class="content">
        {% placeholder "content" %}
    </div>
{% endblock content %}

orient/orient/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}