orient/cup/urls.py
from django.conf.urls import url, patterns

from .views import IndexView, OrganizerView, OrganizerUpdateView, OrganizerCreateView,\
    MarathonDetailView, RunnerDetailView, latest_m

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^or/(?P<pk>\d+)$', OrganizerView.as_view(), name='organizer'),
    url(r'^or-u/(?P<pk>\d+)$', OrganizerUpdateView.as_view(), name='organizer_update'),
    url(r'^or-c', OrganizerCreateView.as_view(), name='organizer_create'),
    url(r'^marathon/(?P<pk>\d+)$', MarathonDetailView.as_view(), name='marathon_runners'),
    url(r'^runner/(?P<pk>\d+)$', RunnerDetailView.as_view(), name='runner'),
    url(r'^latestm$', latest_m, name='latest_m'),
)

orient/orient/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'', include('cadmin.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
    url(r'^cup/', include('cup.urls', namespace='cup')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

orient/cup_plugin/models.py
from django.db import models

from cms.models import CMSPlugin
from cup.models import Organizer, Marathon, Season, Route


class CupPlugin(CMSPlugin):
    organizer = models.ForeignKey(Organizer, verbose_name='Organizer name')
    marathon = models.ForeignKey(Marathon, verbose_name='Marathon')
    name = models.CharField(verbose_name='Adnotation', max_length=255)

    def __str__(self):
        return self.organizer.__str__()


class CupCalendar(CMSPlugin):
    season = models.ForeignKey(Season, verbose_name='Season of Marathon')

    def __str__(self):
        return self.season.__str__()


class CupOrganizer(CMSPlugin):
#    organizer = models.ForeignKey(Organizer, verbose_name='Organizer name')

    def __str__(self):
        return self.organizer.__str__()


class CupMarathon(CMSPlugin):

    def __str__(self):
        return self.marathon.__str__()


class CupRunner(CMSPlugin):

    def __str__(self):
        return self.runner.__str__()

orient/cup_plugin/views.py
from django.shortcuts import render

# Create your views here.

orient/cup_plugin/templates/djangocms_cup/cup_calendar.html
<h1>Puchar Polski w Pieszych Maratonach na Orientację {{ instance.season }}</h1>
<div id="tiles">
    {% for marathon in instance.season.marathons.all %}
        <div class="tile{% if marathon.is_past %} past{% endif %}" number="{{ forloop.counter }}">
{#            <a href="{{ marathon.web }}">#}
{#            <a href="{% url 'cup:marathon_runners' marathon.pk %}">#}
            <a href="/en/zawody/#marathon-id={{ marathon.pk }}">
                <div class="logo"><img src="{{ MEDIA_URL }}{{ marathon.logo_img }}" /></div>
                <div class="name">{{ marathon }}</div>
                <div class="locality">{{ marathon.locality }}</div>
                <div class="date">{{ marathon.start_date }}</div>
            </a>
        </div>
    {% endfor %}
</div>
<div class="clear"></div>

orient/cup_plugin/templates/djangocms_cup/cup_marathon.html
<div id="marathons">
ładuję dane zawodów...
</div>

orient/cup_plugin/templates/djangocms_cup/cup_organizer.html
{% load i18n %}
<h1>{% trans 'Organizer registration' %}</h1>
<form id="registration_form" name="registration_form" method="post" class="cup_form">
    <ul>
        <li>
            {% csrf_token %}
        </li>
        <li>
            <label for="first_name">Imię</label>
            <input id="first_name" type="text" name="first_name"/>
        </li>
        <li>
            <label for="last_name">Nazwisko</label>
            <input id="last_name" type="text" name="last_name"/>
        </li>
        <li>
            <label for="username">Nick</label>
            <input id="username" type="text" name="username"/>
        </li>
        <li>
            <label for="password">Hasło</label>
            <input id="password" type="password" name="password"/>
        </li>
        <li>
            <label for="confirm_password">Powtórz hasło</label>
            <input id="confirm_password" type="password" name="confirm_password"/>
        </li>
        <li>
            <label for="email">E-mail</label>
            <input id="email" type="text" name="email"/>
        </li>
        <li>
            <label for="web">WWW</label>
            <input id="web" type="text" name="web"/>
        </li>
        <li>
            <label for="phone">Telefon</label>
            <input id="phone" type="text" name="phone"/>
        </li>
        <li>
            <label for="desc">Opis</label>
            <textarea id="desc" type="text" name="desc"></textarea>
        </li>
        <li class="checkbox-row">
            <input id="policy" type="checkbox" class="checkbox" name="policy"/>
            <label for="policy">Zgoda na przechowywanie i przetwarzanie danych</label>
        </li>
        <li class="send">
            <input id="send_form" type="submit" name="send_form" value="Wyślij" />
        </li>
    </ul>
</form>

orient/cup_plugin/templates/djangocms_cup/cup_plugin.html
<div>Organizator: {{ instance.organizer }}</div>
<div>web: <a href="{{ instance.organizer.web }}">{{ instance.organizer.web }}</a></div>
<div>opis: {{ instance.organizer.desc }}</div>
<div>Nazwa: {{ instance.name }}</div>

orient/cup_plugin/templates/djangocms_cup/cup_registration.html
<h2>Registration</h2>
<form name="registration_form" action="">
    <ul>
        <li>
            <label for="username">Nick</label>
            <input id="username" type="text" name="username"/>
        </li>
        <li>
            <label for="password">Hasło</label>
            <input id="password" type="password" name="password"/>
        </li>
        <li>
            <label for="password2">Powtórz hasło</label>
            <input id="password2" type="password" name="password2"/>
        </li>
        <li>
            <label for="email">E-mail</label>
            <input id="email" type="text" name="email"/>
        </li>
        <li>
            <label for="first_name">Imię</label>
            <input id="first_name" type="text" name="first_name"/>
        </li>
        <li>
            <label for="last_name">Nazwisko</label>
            <input id="last_name" type="text" name="last_name"/>
        </li>
        <li>
            <label for="gender">Płeć</label>
            <select name="gender">
                <option value=""> - </option>
                <option value="male">Męszczyzna</option>
                <option value="female">Kobieta</option>
            </select>
        </li>
        <li>
            <label for="birth_date">Data urodzenia</label>
            <input id="birth_date" type="text" name="birth_date"/>
        </li>
        <li>
            <label for="place">Miejscowość</label>
            <input id="place" type="text" name="place"/>
        </li>
        <li>
            <input id="send_form" type="submit" name="send_form" value="Wyślij" />
        </li>
    </ul>
</form>

orient/cup_plugin/templates/djangocms_cup/cup_runner.html
<div id="runner">
ładuję dane zawodnika...
</div>